name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
      - run: flutter packages get
      - run: dart run ./tool/test_coverage_create_helper.dart
      - run: flutter test --coverage
      - run: dart run ./tool/test_coverage_filter.dart
      - run: dart run ./tool/test_coverage_validate_percentage.dart
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}